version: "3.10"

services:
  postgres:
    container_name: frs-postgres-db
    restart: always
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - frs-network

  adminer:
    container_name: frs-postgres-dashboard
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - frs-network
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local

networks:
  frs-network:
    driver: bridge
